### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by hAr1x** [Ted4P/Checkers#3]
Guys, it's extremely stupid to not add a license in GitHub. Right now I have the rights to fork this repository and claim it as mine.

**Comment by hyunchoi98** [comment]
"Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided."

Thus we retain all copyright to our project and relevant code, except where prohibited by law. If you were to take such an action to infringe upon our copyright, we can issue a cease and desist letter in order to protect our own copyright under Title 17 of the United States Code. You may view our content, as provided for in the GitHub Terms of Service, but you may not create anything that would use our code in an unauthorized manner. Thank you, and have a nice day.

**Comment by Ted4P** [comment]
Hyun if you could commit the BSD 3 clause to a file called LICENSE.txt that'd be awesome, for whatever reason I forgot or it was removed.
Harry, nice bit of trollin

**Comment by hAr1x** [comment]
Oh here is a license, WTFPL: DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE

**Comment by hAr1x** [comment]
## You need it to support markdown.

Make the license <code>LICENSE.md</code> and update <code>README.md</code>
